### ISSUE TITLE
Small translation misunderstanding

### ISSUE THREAD

**Issue by lolametro** [misenhower/splatoon2.ink#12]
Hi!
I saw that you are using the singular form for "upcoming splatfest" and "recent splatfest", but the German locale is using the plural form. I have fixed this here:

 `        "recent": "Vergangenes Splatfest",
        "upcoming": "Bevorstehendes Splatfest"`

Continue your great work!
Many greetings

**Comment by misenhower** [comment]
Got it, I'll update these now. Thanks for your help!
