### ISSUE TITLE
JSON files have no encoding information in response

### ISSUE THREAD

**Issue by ticky** [misenhower/splatoon2.ink#13]
The JSON data files are returned with no encoding set. They appear to actually contain UTF-8 data, but because no encoding is included in the response, they are treated as ISO-8859-1. Adding [`charset=utf-8`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type) to the Content-Type header (i.e. changing it to `Content-Type: application/json; charset=utf-8`) will fix that problem.

This configuration should be possible from the nginx configuration.

**Comment by misenhower** [comment]
This should be fixed now, it might take a moment for CloudFlare's cache to update but let me know if you notice any other issues here 👍

**Comment by ticky** [comment]
Looking good from here! Thanks for the fix :)

<img width="418" alt="screen shot 2018-03-23 at 11 56 50 am" src="https://user-images.githubusercontent.com/282113/37848416-4c1f302e-2e91-11e8-9006-c8a24732ce04.png">
