### ISSUE TITLE
Weapons for salmon run are broken

### ISSUE THREAD

**Issue by renefloor** [misenhower/splatoon2.ink#17]
I guess Nintendo made some updates because of the octo expansion, but the salmon run weapons are broken.

![afbeelding](https://user-images.githubusercontent.com/15101411/41411841-7fa83718-6fde-11e8-8874-e8d83f0eae94.png)

**Comment by misenhower** [comment]
Thanks! This should now be fixed. Let me know if you see any other issues 😄
