### ISSUE TITLE
Make Twitter image endpoint

### ISSUE THREAD

**Issue by Dog2puppy** [misenhower/splatoon2.ink#21]
An endpoint for getting the Twitter image would be great! I'm currently writing a script to get the current Splatoon 2 ranked rotation and if I could have a image for it to display it would look a lot nicer than the current setup of a notification.

**Comment by misenhower** [comment]
This is kind of an interesting request, could you tell me a little more about where you might end up using this?

Is it only the current image you'd be interested in? For example, if there were endpoints like `/img/schedules.png` and `/img/splatnetgear.png` that just showed whatever the last-posted image on Twitter was, would that satisfy what you're looking for?

**Comment by Dog2puppy** [comment]
For me personally I would be using it as I described; a quick shortcut to get Splatoon 2 stages. 

The example endpoints you listed would work great. It would simplify what I’m doing right now a lot.

**Comment by Dog2puppy** [comment]
Works great! Just have to add it to my Automator action once I have my Mac with me. 
![d7b37d76-a56f-4af3-bda0-6f676a2161d2](https://user-images.githubusercontent.com/13684891/50792367-b4d69e00-1292-11e9-956c-a5284e48e125.png)
![403cc2eb-2287-4b7d-8ce4-3d234ce6fa16](https://user-images.githubusercontent.com/13684891/50792368-b4d69e00-1292-11e9-9240-a3083f8f02cd.png)

**Comment by misenhower** [comment]
Oh wow, that's really cool! Thanks for sharing! 😄
