### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by lolametro** [misenhower/splatoon2.ink#9]
Hello there,

I noticed you added a German translation, even though it is a bit incomplete. I translated the rest of the UI. You can use it, if you want:

`"ui": {
        "about": "Über",
        "map_schedules": "Arenen-Info",
        "get_updates_via_twitter": "Informiere dich über Twitter!",
        "all_upcoming_stages": "Alle bevorstehenden Arenen",
        "disclaimer": "Diese Website steht in keiner Verbindung zu Nintendo. Alle Produktnamen, Logos und Marken sind Eigentum der jeweiligen Inhaber."
    }`

Unfortunately, there is no great translation for the word "schedule" so I used "Info" (just as it is called in the SplatNet app).

And just btw, great work with this website! I'm using it a lot 👍 
Many greetings

**Comment by misenhower** [comment]
Thank you! I will add these in later today.

Thanks for the help!!

**Comment by misenhower** [comment]
Could I ask for your help with a few remaining translations?

* "Original Gear" (shown when you mouse over gear in the SplatNet/TentaWorld gear screen)
* "Upcoming Splatfest" (shown before the Splatfest begins)
* "Recent Splatfest" (shown above the results after the Splatfest ends)

Thanks again!

**Comment by Marionaise** [comment]
"Original Gear" => "Originale Kleidung" (maybe lolametro knows a better translation)
"Upcoming Splatfest" => ""Bevorstehende  Splatfeste"
"Recent Splatfest" => "Vergange Splatfeste"

**Comment by lolametro** [comment]
I would do it as Mario said, but use „Originale Ausrüstung“ for the gear.

Have a nice Wednesday

Am 13.12.2017 um 07:27 schrieb Mario Franze <notifications@github.com<mailto:notifications@github.com>>:


"Original Gear" => "Originale Kleidung" (maybe lolametro knows a better translation)
"Upcoming Splatfest" => ""Bevorstehende Splatfeste"
"Recent Splatfest" => "Vergange Splatfeste"

**Comment by misenhower** [comment]
Should that be "Vergangene Splatfeste"?

![image](https://user-images.githubusercontent.com/1619746/33953767-08fc260c-dfeb-11e7-9f53-0d79a6732b2a.png)

**Comment by Marionaise** [comment]
@misenhower Can I reach you via Discord/TS?

**Comment by misenhower** [comment]
Sure, I'm ike#9992 on Discord.

**Comment by lolametro** [comment]
Yeah, „Vergangene“ is correct!

**Comment by misenhower** [comment]
Thanks again! Feel free to open another issue if there's anything else 😄
